blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://github.com/catchthatrabbit/coreminer/discussions
    about: Discussion about mining on the Core Blockchain.
  - name: Quick Start
    url: https://catchthatrabbit.com/start-mining
    about: To start mining, please follow this guide.
  - name: Support
    url: https://catchthatrabbit.com/contact
    about: Contact support.
