name: CoreMiner docker
on:
  push:
    tags:
      - 'v*'
jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Version
        id: version
        run: echo "tag=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT
      - name: Setup
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/catchthatrabbit/coreminer:${{ steps.version.outputs.tag }} \
            --tag ghcr.io/catchthatrabbit/coreminer:latest \
            --push .
      - name: Verify
        run: docker buildx imagetools inspect ghcr.io/catchthatrabbit/coreminer:latest
